### ISSUE TITLE
Tune trainer with num_sample >= 20 breaks.

### ISSUE THREAD

**Issue by alessiovignoli** [mathysgrapotte/model-check#18]
When running on the cluster with `num_sample=20` in the `MnnTrainer.tune` function the following error is encountered:
  
  ```
(train_mnn pid=47538)   return F.mse_loss(input, target, reduction=self.reduction)
  (train_mnn pid=47551) /usr/local/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
   .
   .
   .
  (train_mnn pid=48541)   return F.mse_loss(input, target, reduction=self.reduction)
  (train_mnn pid=48565) /usr/local/lib/python3.10/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  (train_mnn pid=48565)   return F.mse_loss(input, target, reduction=self.reduction)
  2023-11-28 10:23:46,967	INFO tune.py:798 -- Total run time: 36.51 seconds (35.98 seconds for the tuning loop).
  Traceback (most recent call last):
    File "/nfs/users/cn/avignoli/model-check/bin/launch_training.py", line 78, in <module>
      main(args.infasta, args.batch_size, args.shuffle, args.seq_len, args.epochs, args.filter_size, args.optimizer_lr, args.modules_version)
    File "/nfs/users/cn/avignoli/model-check/bin/launch_training.py", line 59, in main
      dfs = mnn_trainer.tune(search_space=config, num_samples=20)
    File "/nfs/users/cn/avignoli/model-check/bin/src/learner/tune_trainer.py", line 205, in tune
      self.model.load_state_dict(checkpoint['model_state_dict'])
    File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
      raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
  RuntimeError: Error(s) in loading state_dict for Net:
  	Unexpected key(s) in state_dict: "blocks.0.conv.weight", "blocks.0.dense.weight", "blocks.0.dense.bias". 
  	size mismatch for linear.weight: copying a param with shape torch.Size([1, 2]) from checkpoint, the shape in current model is torch.Size([1, 1]).


```

**Comment by mathysgrapotte** [comment]
@alessiovignoli has discovered that this was most likely due to the fact that model has ability to add blocks during training, which creates a difference between the saved current model architecture and the one used for training
